#!/bin/bash

ARGS=$@
function error {
  echo "epgdump c27 *.ts -" 1>&2
  exit 1
}

if [ "$1" != "c27" ]; then
  error
fi

if [ "$2" == "" ]; then
  error
fi

if [ "$3" != "-" ]; then
  error
fi

if [ -f "$2" ]; then
  cat "$(dirname $0)/sample.xml"
fi
exit 0
